# Generated by Django 3.1.7 on 2021-03-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20210328_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Article',
        ),
    ]
