# Generated by Django 3.1.7 on 2021-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20210329_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dandelion',
            name='public',
        ),
        migrations.AddField(
            model_name='article',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dandelion',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dandelion',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
